name: Energy Systems CI Pipeline  # Workflow name

on:  # Trigger for the workflow
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch

jobs:  # The list of jobs in the workflow
  build:
    runs-on: ubuntu-latest  # Environment for this job

    steps:  # The steps to execute in this job
      - name: Checkout code  # Step to check out the code
        uses: actions/checkout@v2

      - name: Set up Python  # Step to set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies  # Step to install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests  # Step to run your tests
        run: |
          pytest

  deploy:
    runs-on: ubuntu-latest  # Deployment job runs on the same environment
    needs: build  # Ensure the build job is successful before deploying
    if: success()  # Deploy only if the build is successful

    steps:
      - name: Deploy to Cloud  # Example deployment step
        run: |
          echo "Deploying to cloud platform..."

      - name: Notify stakeholders  # Example notification step
        run: |
          echo "Sending notifications to stakeholders..."
